### ISSUE TITLE
Can i use this for LittleFs? 

### ISSUE THREAD

**Issue by demirschmid61** [gb88/BLEOTA#2]
@gb88 

As I am using littlefs file system in my project, can i use this library for littlefs instead of spiffs?

**Comment by gb88** [comment]
Yes you can use it, you and will work, be carefull that in case of SPIFFS/LittleFS as soon the OTA process start the partition will be erased, so in case of disconnection, errors, or invalid signature (for the sicure version) the partition will be empty, this is due to the implementation of Update library [https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/src/Updater.cpp#L391](url) and the is no rollback mechanism.
